version: "3.5"
services:
  codeflix_rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672 #Interface
      - 5672:5672 #Rabbitmq
    volumes:
      - volume_rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      - codeflix_rabbitmq

networks:
  codeflix_rabbitmq:
    driver: bridge

volumes:
  volume_rabbitmq:
    driver: local
